<?php
/** @package Metadb::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("HostMysqlAttributeMap.php");

/**
 * HostMysqlAttributeDAO provides object-oriented access to the host_mysql_attributes table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Metadb::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class HostMysqlAttributeDAO extends Phreezable
{
	/** @var int */
	public $HostId;

	/** @var int */
	public $MysqlAttributeId;

	/** @var string */
	public $Value;

	/** @var timestamp */
	public $UpdatedAt;



}
?>